# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(595, 695)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.formLayout = QtWidgets.QFormLayout(self.centralWidget)
        self.formLayout.setContentsMargins(11, 11, 11, 11)
        self.formLayout.setSpacing(6)
        self.formLayout.setObjectName("formLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.date_urlaub_von_3 = QtWidgets.QDateEdit(self.centralWidget)
        self.date_urlaub_von_3.setObjectName("date_urlaub_von_3")
        self.gridLayout_2.addWidget(self.date_urlaub_von_3, 3, 1, 1, 1)
        self.label_urlaub_bis_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_urlaub_bis_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_urlaub_bis_3.setObjectName("label_urlaub_bis_3")
        self.gridLayout_2.addWidget(self.label_urlaub_bis_3, 3, 2, 1, 1)
        self.date_urlaub_bis_1 = QtWidgets.QDateEdit(self.centralWidget)
        self.date_urlaub_bis_1.setObjectName("date_urlaub_bis_1")
        self.gridLayout_2.addWidget(self.date_urlaub_bis_1, 1, 3, 1, 1)
        self.date_zeitraum_bis = QtWidgets.QDateEdit(self.centralWidget)
        self.date_zeitraum_bis.setObjectName("date_zeitraum_bis")
        self.gridLayout_2.addWidget(self.date_zeitraum_bis, 0, 3, 1, 1)
        self.date_urlaub_bis_3 = QtWidgets.QDateEdit(self.centralWidget)
        self.date_urlaub_bis_3.setObjectName("date_urlaub_bis_3")
        self.gridLayout_2.addWidget(self.date_urlaub_bis_3, 3, 3, 1, 1)
        self.label_urlaub_von_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_urlaub_von_3.setObjectName("label_urlaub_von_3")
        self.gridLayout_2.addWidget(self.label_urlaub_von_3, 3, 0, 1, 1)
        self.label_urlaub_bis_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_urlaub_bis_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_urlaub_bis_2.setObjectName("label_urlaub_bis_2")
        self.gridLayout_2.addWidget(self.label_urlaub_bis_2, 2, 2, 1, 1)
        self.label_urlaub_bis_1 = QtWidgets.QLabel(self.centralWidget)
        self.label_urlaub_bis_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_urlaub_bis_1.setObjectName("label_urlaub_bis_1")
        self.gridLayout_2.addWidget(self.label_urlaub_bis_1, 1, 2, 1, 1)
        self.label_zeitraum_von = QtWidgets.QLabel(self.centralWidget)
        self.label_zeitraum_von.setObjectName("label_zeitraum_von")
        self.gridLayout_2.addWidget(self.label_zeitraum_von, 0, 0, 1, 1)
        self.label_zeitraum_bis = QtWidgets.QLabel(self.centralWidget)
        self.label_zeitraum_bis.setAlignment(QtCore.Qt.AlignCenter)
        self.label_zeitraum_bis.setObjectName("label_zeitraum_bis")
        self.gridLayout_2.addWidget(self.label_zeitraum_bis, 0, 2, 1, 1)
        self.date_urlaub_von_1 = QtWidgets.QDateEdit(self.centralWidget)
        self.date_urlaub_von_1.setObjectName("date_urlaub_von_1")
        self.gridLayout_2.addWidget(self.date_urlaub_von_1, 1, 1, 1, 1)
        self.date_zeitraum_von = QtWidgets.QDateEdit(self.centralWidget)
        self.date_zeitraum_von.setObjectName("date_zeitraum_von")
        self.gridLayout_2.addWidget(self.date_zeitraum_von, 0, 1, 1, 1)
        self.date_urlaub_von_2 = QtWidgets.QDateEdit(self.centralWidget)
        self.date_urlaub_von_2.setObjectName("date_urlaub_von_2")
        self.gridLayout_2.addWidget(self.date_urlaub_von_2, 2, 1, 1, 1)
        self.date_urlaub_bis_2 = QtWidgets.QDateEdit(self.centralWidget)
        self.date_urlaub_bis_2.setObjectName("date_urlaub_bis_2")
        self.gridLayout_2.addWidget(self.date_urlaub_bis_2, 2, 3, 1, 1)
        self.label_urlaub_von_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_urlaub_von_2.setObjectName("label_urlaub_von_2")
        self.gridLayout_2.addWidget(self.label_urlaub_von_2, 2, 0, 1, 1)
        self.label_urlaub_von_1 = QtWidgets.QLabel(self.centralWidget)
        self.label_urlaub_von_1.setObjectName("label_urlaub_von_1")
        self.gridLayout_2.addWidget(self.label_urlaub_von_1, 1, 0, 1, 1)
        self.label_urlaub_von_4 = QtWidgets.QLabel(self.centralWidget)
        self.label_urlaub_von_4.setObjectName("label_urlaub_von_4")
        self.gridLayout_2.addWidget(self.label_urlaub_von_4, 4, 0, 1, 1)
        self.date_urlaub_von_4 = QtWidgets.QDateEdit(self.centralWidget)
        self.date_urlaub_von_4.setObjectName("date_urlaub_von_4")
        self.gridLayout_2.addWidget(self.date_urlaub_von_4, 4, 1, 1, 1)
        self.date_urlaub_bis_4 = QtWidgets.QDateEdit(self.centralWidget)
        self.date_urlaub_bis_4.setObjectName("date_urlaub_bis_4")
        self.gridLayout_2.addWidget(self.date_urlaub_bis_4, 4, 3, 1, 1)
        self.label_urlaub_bis_4 = QtWidgets.QLabel(self.centralWidget)
        self.label_urlaub_bis_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_urlaub_bis_4.setObjectName("label_urlaub_bis_4")
        self.gridLayout_2.addWidget(self.label_urlaub_bis_4, 4, 2, 1, 1)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.SpanningRole, self.gridLayout_2)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_montag = QtWidgets.QLabel(self.centralWidget)
        self.label_montag.setAlignment(QtCore.Qt.AlignCenter)
        self.label_montag.setObjectName("label_montag")
        self.gridLayout_3.addWidget(self.label_montag, 0, 0, 1, 1)
        self.spin_dienstag = QtWidgets.QSpinBox(self.centralWidget)
        self.spin_dienstag.setMaximum(24)
        self.spin_dienstag.setObjectName("spin_dienstag")
        self.gridLayout_3.addWidget(self.spin_dienstag, 1, 1, 1, 1)
        self.label_samstag = QtWidgets.QLabel(self.centralWidget)
        self.label_samstag.setAlignment(QtCore.Qt.AlignCenter)
        self.label_samstag.setObjectName("label_samstag")
        self.gridLayout_3.addWidget(self.label_samstag, 0, 5, 1, 1)
        self.label_donnerstag = QtWidgets.QLabel(self.centralWidget)
        self.label_donnerstag.setAlignment(QtCore.Qt.AlignCenter)
        self.label_donnerstag.setObjectName("label_donnerstag")
        self.gridLayout_3.addWidget(self.label_donnerstag, 0, 3, 1, 1)
        self.spin_montag = QtWidgets.QSpinBox(self.centralWidget)
        self.spin_montag.setMaximum(24)
        self.spin_montag.setObjectName("spin_montag")
        self.gridLayout_3.addWidget(self.spin_montag, 1, 0, 1, 1)
        self.spin_freitag = QtWidgets.QSpinBox(self.centralWidget)
        self.spin_freitag.setMaximum(24)
        self.spin_freitag.setObjectName("spin_freitag")
        self.gridLayout_3.addWidget(self.spin_freitag, 1, 4, 1, 1)
        self.label_freitag = QtWidgets.QLabel(self.centralWidget)
        self.label_freitag.setAlignment(QtCore.Qt.AlignCenter)
        self.label_freitag.setObjectName("label_freitag")
        self.gridLayout_3.addWidget(self.label_freitag, 0, 4, 1, 1)
        self.label_dienstag = QtWidgets.QLabel(self.centralWidget)
        self.label_dienstag.setAlignment(QtCore.Qt.AlignCenter)
        self.label_dienstag.setObjectName("label_dienstag")
        self.gridLayout_3.addWidget(self.label_dienstag, 0, 1, 1, 1)
        self.label_mittwoch = QtWidgets.QLabel(self.centralWidget)
        self.label_mittwoch.setAlignment(QtCore.Qt.AlignCenter)
        self.label_mittwoch.setObjectName("label_mittwoch")
        self.gridLayout_3.addWidget(self.label_mittwoch, 0, 2, 1, 1)
        self.spin_donnerstag = QtWidgets.QSpinBox(self.centralWidget)
        self.spin_donnerstag.setMaximum(24)
        self.spin_donnerstag.setObjectName("spin_donnerstag")
        self.gridLayout_3.addWidget(self.spin_donnerstag, 1, 3, 1, 1)
        self.spin_mittwoch = QtWidgets.QSpinBox(self.centralWidget)
        self.spin_mittwoch.setMaximum(24)
        self.spin_mittwoch.setObjectName("spin_mittwoch")
        self.gridLayout_3.addWidget(self.spin_mittwoch, 1, 2, 1, 1)
        self.label_sonntag = QtWidgets.QLabel(self.centralWidget)
        self.label_sonntag.setAlignment(QtCore.Qt.AlignCenter)
        self.label_sonntag.setObjectName("label_sonntag")
        self.gridLayout_3.addWidget(self.label_sonntag, 0, 6, 1, 1)
        self.spin_sonntag = QtWidgets.QSpinBox(self.centralWidget)
        self.spin_sonntag.setMaximum(24)
        self.spin_sonntag.setObjectName("spin_sonntag")
        self.gridLayout_3.addWidget(self.spin_sonntag, 1, 6, 1, 1)
        self.spin_samstag = QtWidgets.QSpinBox(self.centralWidget)
        self.spin_samstag.setMaximum(24)
        self.spin_samstag.setObjectName("spin_samstag")
        self.gridLayout_3.addWidget(self.spin_samstag, 1, 5, 1, 1)
        self.formLayout.setLayout(4, QtWidgets.QFormLayout.SpanningRole, self.gridLayout_3)
        self.button_nettostunden_berechnen = QtWidgets.QPushButton(self.centralWidget)
        self.button_nettostunden_berechnen.setObjectName("button_nettostunden_berechnen")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.SpanningRole, self.button_nettostunden_berechnen)
        self.text_dialog = QtWidgets.QTextBrowser(self.centralWidget)
        self.text_dialog.setObjectName("text_dialog")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.SpanningRole, self.text_dialog)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, 2, 0, -1)
        self.horizontalLayout_5.setSpacing(300)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.button_help = QtWidgets.QPushButton(self.centralWidget)
        self.button_help.setObjectName("button_help")
        self.horizontalLayout_5.addWidget(self.button_help)
        self.button_about = QtWidgets.QPushButton(self.centralWidget)
        self.button_about.setObjectName("button_about")
        self.horizontalLayout_5.addWidget(self.button_about)
        self.formLayout.setLayout(7, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout_5)
        self.label_arbeiszeiten = QtWidgets.QLabel(self.centralWidget)
        self.label_arbeiszeiten.setObjectName("label_arbeiszeiten")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.label_arbeiszeiten)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(0, 0, -1, -1)
        self.horizontalLayout_6.setSpacing(5)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_sonderzeit = QtWidgets.QLabel(self.centralWidget)
        self.label_sonderzeit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_sonderzeit.setObjectName("label_sonderzeit")
        self.horizontalLayout_6.addWidget(self.label_sonderzeit)
        self.spin_sonderzeit = QtWidgets.QSpinBox(self.centralWidget)
        self.spin_sonderzeit.setMaximum(999)
        self.spin_sonderzeit.setObjectName("spin_sonderzeit")
        self.horizontalLayout_6.addWidget(self.spin_sonderzeit)
        self.button_was_ist_sonderzeit = QtWidgets.QPushButton(self.centralWidget)
        self.button_was_ist_sonderzeit.setObjectName("button_was_ist_sonderzeit")
        self.horizontalLayout_6.addWidget(self.button_was_ist_sonderzeit)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(0, 0, -1, -1)
        self.horizontalLayout_7.setSpacing(250)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.button_urlaub_hinzufuegen = QtWidgets.QPushButton(self.centralWidget)
        self.button_urlaub_hinzufuegen.setObjectName("button_urlaub_hinzufuegen")
        self.horizontalLayout_7.addWidget(self.button_urlaub_hinzufuegen)
        self.button_urlaub_entfernen = QtWidgets.QPushButton(self.centralWidget)
        self.button_urlaub_entfernen.setObjectName("button_urlaub_entfernen")
        self.horizontalLayout_7.addWidget(self.button_urlaub_entfernen)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout_7)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 595, 22))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setMovable(False)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.date_zeitraum_von, self.date_zeitraum_bis)
        MainWindow.setTabOrder(self.date_zeitraum_bis, self.date_urlaub_von_1)
        MainWindow.setTabOrder(self.date_urlaub_von_1, self.date_urlaub_bis_1)
        MainWindow.setTabOrder(self.date_urlaub_bis_1, self.date_urlaub_von_2)
        MainWindow.setTabOrder(self.date_urlaub_von_2, self.date_urlaub_bis_2)
        MainWindow.setTabOrder(self.date_urlaub_bis_2, self.date_urlaub_von_3)
        MainWindow.setTabOrder(self.date_urlaub_von_3, self.date_urlaub_bis_3)
        MainWindow.setTabOrder(self.date_urlaub_bis_3, self.date_urlaub_von_4)
        MainWindow.setTabOrder(self.date_urlaub_von_4, self.date_urlaub_bis_4)
        MainWindow.setTabOrder(self.date_urlaub_bis_4, self.button_urlaub_hinzufuegen)
        MainWindow.setTabOrder(self.button_urlaub_hinzufuegen, self.button_urlaub_entfernen)
        MainWindow.setTabOrder(self.button_urlaub_entfernen, self.spin_sonderzeit)
        MainWindow.setTabOrder(self.spin_sonderzeit, self.button_was_ist_sonderzeit)
        MainWindow.setTabOrder(self.button_was_ist_sonderzeit, self.spin_montag)
        MainWindow.setTabOrder(self.spin_montag, self.spin_dienstag)
        MainWindow.setTabOrder(self.spin_dienstag, self.spin_mittwoch)
        MainWindow.setTabOrder(self.spin_mittwoch, self.spin_donnerstag)
        MainWindow.setTabOrder(self.spin_donnerstag, self.spin_freitag)
        MainWindow.setTabOrder(self.spin_freitag, self.spin_samstag)
        MainWindow.setTabOrder(self.spin_samstag, self.spin_sonntag)
        MainWindow.setTabOrder(self.spin_sonntag, self.button_nettostunden_berechnen)
        MainWindow.setTabOrder(self.button_nettostunden_berechnen, self.text_dialog)
        MainWindow.setTabOrder(self.text_dialog, self.button_help)
        MainWindow.setTabOrder(self.button_help, self.button_about)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_urlaub_bis_3.setText(_translate("MainWindow", "bis"))
        self.label_urlaub_von_3.setText(_translate("MainWindow", "Urlaub/Krank von"))
        self.label_urlaub_bis_2.setText(_translate("MainWindow", "bis"))
        self.label_urlaub_bis_1.setText(_translate("MainWindow", "bis"))
        self.label_zeitraum_von.setText(_translate("MainWindow", "Zeitraum von"))
        self.label_zeitraum_bis.setText(_translate("MainWindow", "bis"))
        self.label_urlaub_von_2.setText(_translate("MainWindow", "Urlaub/Krank von"))
        self.label_urlaub_von_1.setText(_translate("MainWindow", "Urlaub/Krank von"))
        self.label_urlaub_von_4.setText(_translate("MainWindow", "Urlaub/Krank von"))
        self.label_urlaub_bis_4.setText(_translate("MainWindow", "bis"))
        self.label_montag.setText(_translate("MainWindow", "Montag"))
        self.label_samstag.setText(_translate("MainWindow", "Samstag"))
        self.label_donnerstag.setText(_translate("MainWindow", "Donnerstag"))
        self.label_freitag.setText(_translate("MainWindow", "Freitag"))
        self.label_dienstag.setText(_translate("MainWindow", "Dienstag"))
        self.label_mittwoch.setText(_translate("MainWindow", "Mittwoch"))
        self.label_sonntag.setText(_translate("MainWindow", "Sonntag"))
        self.button_nettostunden_berechnen.setText(_translate("MainWindow", "Nettostunden Berechnen"))
        self.button_help.setText(_translate("MainWindow", "Help"))
        self.button_about.setText(_translate("MainWindow", "About"))
        self.label_arbeiszeiten.setText(_translate("MainWindow", "Arbeitszeiten h/Tag"))
        self.label_sonderzeit.setText(_translate("MainWindow", "Sonderzeit in Stunden:"))
        self.button_was_ist_sonderzeit.setText(_translate("MainWindow", "Was ist eine Sonderzeit?"))
        self.button_urlaub_hinzufuegen.setText(_translate("MainWindow", "Urlaub/Krank hinzufügen"))
        self.button_urlaub_entfernen.setText(_translate("MainWindow", "Urlaub/Krank entfernen"))

