# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(558, 666)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.pushButton = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton.setGeometry(QtCore.QRect(0, 580, 88, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_2.setGeometry(QtCore.QRect(470, 580, 88, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.dateEdit = QtWidgets.QDateEdit(self.centralWidget)
        self.dateEdit.setGeometry(QtCore.QRect(100, 30, 110, 26))
        self.dateEdit.setObjectName("dateEdit")
        self.dateEdit_2 = QtWidgets.QDateEdit(self.centralWidget)
        self.dateEdit_2.setGeometry(QtCore.QRect(290, 30, 110, 26))
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.dateEdit_3 = QtWidgets.QDateEdit(self.centralWidget)
        self.dateEdit_3.setGeometry(QtCore.QRect(100, 60, 110, 26))
        self.dateEdit_3.setObjectName("dateEdit_3")
        self.dateEdit_4 = QtWidgets.QDateEdit(self.centralWidget)
        self.dateEdit_4.setGeometry(QtCore.QRect(290, 60, 110, 26))
        self.dateEdit_4.setObjectName("dateEdit_4")
        self.spinBox = QtWidgets.QSpinBox(self.centralWidget)
        self.spinBox.setGeometry(QtCore.QRect(10, 170, 47, 26))
        self.spinBox.setObjectName("spinBox")
        self.label_ZeitraumVon = QtWidgets.QLabel(self.centralWidget)
        self.label_ZeitraumVon.setGeometry(QtCore.QRect(10, 30, 81, 16))
        self.label_ZeitraumVon.setObjectName("label_ZeitraumVon")
        self.label_ZeitraumBis = QtWidgets.QLabel(self.centralWidget)
        self.label_ZeitraumBis.setGeometry(QtCore.QRect(250, 30, 21, 16))
        self.label_ZeitraumBis.setObjectName("label_ZeitraumBis")
        self.label_UrlaubVon = QtWidgets.QLabel(self.centralWidget)
        self.label_UrlaubVon.setGeometry(QtCore.QRect(20, 60, 61, 16))
        self.label_UrlaubVon.setObjectName("label_UrlaubVon")
        self.label_UrlaubBis = QtWidgets.QLabel(self.centralWidget)
        self.label_UrlaubBis.setGeometry(QtCore.QRect(250, 60, 21, 16))
        self.label_UrlaubBis.setObjectName("label_UrlaubBis")
        self.label_Arbeitszeiten = QtWidgets.QLabel(self.centralWidget)
        self.label_Arbeitszeiten.setGeometry(QtCore.QRect(10, 120, 121, 16))
        self.label_Arbeitszeiten.setObjectName("label_Arbeitszeiten")
        self.spinBox_2 = QtWidgets.QSpinBox(self.centralWidget)
        self.spinBox_2.setGeometry(QtCore.QRect(90, 170, 47, 26))
        self.spinBox_2.setObjectName("spinBox_2")
        self.spinBox_3 = QtWidgets.QSpinBox(self.centralWidget)
        self.spinBox_3.setGeometry(QtCore.QRect(170, 170, 47, 26))
        self.spinBox_3.setObjectName("spinBox_3")
        self.spinBox_4 = QtWidgets.QSpinBox(self.centralWidget)
        self.spinBox_4.setGeometry(QtCore.QRect(250, 170, 47, 26))
        self.spinBox_4.setObjectName("spinBox_4")
        self.spinBox_5 = QtWidgets.QSpinBox(self.centralWidget)
        self.spinBox_5.setGeometry(QtCore.QRect(340, 170, 47, 26))
        self.spinBox_5.setObjectName("spinBox_5")
        self.spinBox_6 = QtWidgets.QSpinBox(self.centralWidget)
        self.spinBox_6.setGeometry(QtCore.QRect(420, 170, 47, 26))
        self.spinBox_6.setObjectName("spinBox_6")
        self.spinBox_7 = QtWidgets.QSpinBox(self.centralWidget)
        self.spinBox_7.setGeometry(QtCore.QRect(500, 170, 47, 26))
        self.spinBox_7.setObjectName("spinBox_7")
        self.label_Montag = QtWidgets.QLabel(self.centralWidget)
        self.label_Montag.setGeometry(QtCore.QRect(10, 150, 58, 16))
        self.label_Montag.setObjectName("label_Montag")
        self.label_Dienstag = QtWidgets.QLabel(self.centralWidget)
        self.label_Dienstag.setGeometry(QtCore.QRect(90, 150, 58, 16))
        self.label_Dienstag.setObjectName("label_Dienstag")
        self.label_Mittwoch = QtWidgets.QLabel(self.centralWidget)
        self.label_Mittwoch.setGeometry(QtCore.QRect(170, 150, 58, 16))
        self.label_Mittwoch.setObjectName("label_Mittwoch")
        self.label_Samstag = QtWidgets.QLabel(self.centralWidget)
        self.label_Samstag.setGeometry(QtCore.QRect(420, 150, 58, 16))
        self.label_Samstag.setObjectName("label_Samstag")
        self.label_Donnerstag = QtWidgets.QLabel(self.centralWidget)
        self.label_Donnerstag.setGeometry(QtCore.QRect(250, 150, 70, 16))
        self.label_Donnerstag.setObjectName("label_Donnerstag")
        self.label_Sonntag = QtWidgets.QLabel(self.centralWidget)
        self.label_Sonntag.setGeometry(QtCore.QRect(500, 150, 58, 16))
        self.label_Sonntag.setObjectName("label_Sonntag")
        self.label_Freitag = QtWidgets.QLabel(self.centralWidget)
        self.label_Freitag.setGeometry(QtCore.QRect(340, 150, 58, 16))
        self.label_Freitag.setObjectName("label_Freitag")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_3.setGeometry(QtCore.QRect(190, 220, 170, 30))
        self.pushButton_3.setObjectName("pushButton_3")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 558, 22))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        MainWindow.insertToolBarBreak(self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Help"))
        self.pushButton_2.setText(_translate("MainWindow", "About"))
        self.label_ZeitraumVon.setText(_translate("MainWindow", "Zeitraum von"))
        self.label_ZeitraumBis.setText(_translate("MainWindow", "bis"))
        self.label_UrlaubVon.setText(_translate("MainWindow", "Urlaub von"))
        self.label_UrlaubBis.setText(_translate("MainWindow", "bis"))
        self.label_Arbeitszeiten.setText(_translate("MainWindow", "Arbeitszeiten h/Tag"))
        self.label_Montag.setText(_translate("MainWindow", "Montag"))
        self.label_Dienstag.setText(_translate("MainWindow", "Dienstag"))
        self.label_Mittwoch.setText(_translate("MainWindow", "Mittwoch"))
        self.label_Samstag.setText(_translate("MainWindow", "Samstag"))
        self.label_Donnerstag.setText(_translate("MainWindow", "Donnerstag"))
        self.label_Sonntag.setText(_translate("MainWindow", "Sonntag"))
        self.label_Freitag.setText(_translate("MainWindow", "Freitag"))
        self.pushButton_3.setText(_translate("MainWindow", "Nettostunden Berechnen"))

